sudo: required
services:
  - docker

before_install:
  - docker build -t bartoszgajda55/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run bartoszgajda55/react-test npm test -- --coverage

after_success:
  - docker build -t bartoszgajda55/multi-client ./client
  - docker build -t bartoszgajda55/multi-nginx ./nginx
  - docker build -t bartoszgajda55/multi-server ./server
  - docker build -t bartoszgajda55/multi-worker ./worker
